# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service 
  namespace: default
spec:
  selector:
    component: web
  type: ClusterIP
  ports:
    - port: 3000 
      targetPort: 3000
---
