# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service 
  namespace: default
spec:
  selector:
    component: server
  type: ClusterIP
  ports:
    - port: 5000 
      targetPort: 5000
---

