name: Deploy MultiDocker
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin 
      - run: ls -R
      - run: docker build -t flaviolcordeiro/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true flaviolcordeiro/react-test npm test

      - run: docker build -t flaviolcordeiro/multi-client ./client
      - run: docker build -t flaviolcordeiro/multi-nginx ./nginx
      - run: docker build -t flaviolcordeiro/multi-server ./server
      - run: docker build -t flaviolcordeiro/multi-worker ./worker

      - run: docker push flaviolcordeiro/multi-client
      - run: docker push flaviolcordeiro/multi-nginx
      - run: docker push flaviolcordeiro/multi-server
      - run: docker push flaviolcordeiro/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v18
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     application_name: multi-docker
      #     environment_name: Multi-docker-env
      #     existing_bucket_name: elasticbeanstalk-eu-north-1-182399683010
      #     region: eu-north-1
      #     version_label: ${{ github.sha }}
      #     deployment_package: deploy.zip
